- .github/workflows/auto-build.yml
- packages/capture/package.json
- packages/capture/src/index.ts
- packages/oas/package.json
- packages/openapi-sampler/package.json
- packages/postman/package.json
> fix(*): include dist folder into the package

- packages/capture/tsconfig.build.json
> fix(capture): disable resolving json module

- .codeclimate.yml
- .eslintrc.js
- .github/workflows/auto-build.yml
- packages/capture/package.json
- packages/oas/package.json
- packages/openapi-sampler/package.json
- packages/validator/package.json
- rollup.config.js
- utilizing cross-env
- rollup workaround (rollup/rollup-plugin-commonjs/issues/361#issuecomment-445214136)
> fix(build): cross-platform fixes

- packages/validator/src/validator/PostmanValidator.ts
> fix(validator): remove redundant url dependency

- packages/validator/src/index.ts
> fix(validator): re-export ErrorObject

- packages/capture/package.json
- packages/editor/package.json
- packages/oas/package.json
- packages/openapi-sampler/package.json
- packages/postman/package.json
- packages/types/README.md
- packages/types/package.json
- packages/validator/package.json
> docs: specify a dedicated homepage for each package

- packages/validator/src/humanizer/formatters/ObjectFormatter.ts
- packages/validator/src/humanizer/formatters/TypeFormatter.ts
- packages/validator/src/humanizer/formatters/WordingHelper.ts
- packages/validator/tests/error-humanizer.spec.ts
> fix(validator): wording for `additionalProperty` violation in multiple properties case

- packages/editor/src/editor/oas/BaseOasParameterObjectsParser.ts
- packages/editor/src/editor/oas/v2/OasV2ParameterObjectsParser.ts
- packages/editor/src/editor/oas/v3/OasV3ParameterObjectsParser.ts
- packages/editor/tests/oas2-sample1.result.json
- packages/editor/tests/oas2.spec.ts
- packages/editor/tests/oas3.spec.ts
- packages/editor/tests/postman.spec.ts
> fix(editor): `setValue` for body parameters

- packages/editor/src/editor/oas/BaseOasParameterObjectsParser.ts
- packages/editor/src/editor/oas/v2/OasV2ParameterObjectsParser.ts
- packages/editor/src/editor/oas/v3/OasV3ParameterObjectsParser.ts
- packages/editor/tests/oas2-sample1.result.json
- packages/editor/tests/oas2.spec.ts
> feat(editor): unified oas request body representation

- packages/validator/README.md
- packages/validator/src/humanizer/ErrorHumanizer.ts
- packages/validator/src/humanizer/HumanizedError.ts
- packages/validator/src/humanizer/index.ts
- packages/validator/tests/error-humanizer.spec.ts
> feat(validator): error message parts meta

- packages/editor/src/editor/postman/PostmanEditor.ts
- packages/editor/tests/postman.spec.ts
> fix(editor): npe in `PostmanUrlParser`

- packages/oas/package-lock.json
- packages/oas/package.json
- packages/oas/src/converter/DefaultConverter.ts
- packages/oas/src/index.ts
- packages/oas/src/utils/index.ts
- packages/postman/package-lock.json
- packages/postman/package.json
- packages/postman/src/converter/Converter.ts
- packages/postman/src/converter/DefaultConverter.ts
- packages/postman/src/index.ts
> perf(*): get rid of the validator from converters

- packages/validator/src/schemas/openapi/v3.0.0.json
- packages/validator/tests/oas.spec.ts
> fix(validator): verify if `servers` contains at least one item

- packages/validator/src/schemas/har/v1.2.json
- packages/validator/tests/har.spec.ts
> fix(validator): improve `serverIPAddress` schema

- packages/validator/src/humanizer/ErrorHumanizer.ts
- packages/validator/src/humanizer/formatters/CustomErrorMessageFormatter.ts
- packages/validator/src/humanizer/formatters/index.ts
- packages/validator/tests/error-humanizer.spec.ts
> fix(validator): property names in custom error messages

- packages/validator/src/schemas/postman/v2.0.0.json
- packages/validator/src/schemas/postman/v2.1.0.json
- packages/validator/tests/error-humanizer.spec.ts
- packages/validator/tests/postman.spec.ts
> fix(validator): improve the validator to check if no items in Postman collection

- packages/postman/src/converter/DefaultConverter.ts
- packages/postman/src/parser/EnvVariableParser.ts
> fix(validator): cast types while using substitution variables

- packages/validator/src/humanizer/ErrorHumanizer.ts
- packages/validator/src/humanizer/formatters/ArrayFormatter.ts
- packages/validator/src/humanizer/formatters/BaseFormatter.ts
- packages/validator/src/humanizer/formatters/CustomErrorMessageFormatter.ts
- packages/validator/src/humanizer/formatters/Formatter.ts
- packages/validator/src/humanizer/formatters/NumericFormatter.ts
- packages/validator/src/humanizer/formatters/ObjectFormatter.ts
- packages/validator/src/humanizer/formatters/StringFormatter.ts
- packages/validator/src/humanizer/formatters/TypeFormatter.ts
- packages/validator/src/humanizer/formatters/WordingHelper.ts
- packages/validator/tests/error-humanizer.spec.ts
> fix(validator): better humanized messages for array targets

- packages/validator/src/schemas/openapi/v3.0.0.json
- packages/validator/tests/error-humanizer.spec.ts
- packages/validator/tests/oas.spec.ts
> fix(validator): adding schema restrictions for oas3 servers url

- packages/validator/tests/fixtures/har.gh-75.json
> test(validator): more test cases for less strict har schema

- packages/oas/src/converter/DefaultConverter.ts
> fix(oas): produce content-type on base of consumers

- packages/oas/src/converter/DefaultConverter.ts
- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/servers-with-variables.oas.yaml
> refactor(oas): use URL template substitution to represent  servers

- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/github.swagger.result.json
- packages/oas/tests/fixtures/multipart.oas.result.json
- packages/oas/tests/fixtures/petstore.oas.result.json
- packages/oas/tests/fixtures/refs.oas.result.json
- packages/oas/tests/fixtures/servers-with-variables.oas.result.json
- packages/openapi-sampler/package-lock.json
- packages/openapi-sampler/package.json
- packages/openapi-sampler/src/samplers/ArraySampler.ts
- packages/openapi-sampler/src/samplers/BooleanSampler.ts
- packages/openapi-sampler/src/samplers/NumberSampler.ts
- packages/openapi-sampler/src/samplers/Sampler.ts
- packages/openapi-sampler/src/samplers/StringSampler.ts
- packages/openapi-sampler/src/traverse/DefaultTraverse.ts
- packages/openapi-sampler/src/traverse/Traverse.ts
- packages/openapi-sampler/src/utils.ts
- packages/openapi-sampler/tests/detection.spec.ts
- packages/openapi-sampler/tests/example.spec.ts
- packages/openapi-sampler/tests/number.spec.ts
- packages/openapi-sampler/tests/objects.spec.ts
- packages/openapi-sampler/tests/oneOfAnyOf.spec.ts
- packages/openapi-sampler/tests/primitives.spec.ts
- packages/openapi-sampler/tests/string.spec.ts
> fix(openapi-sampler): deterministic output

- packages/core/README.md
- packages/core/src/utils/url.ts
- packages/core/tests/normalize-url.spec.ts
> feat(core): new utilities

- packages/core/src/importers/BaseImporter.ts
- packages/core/src/importers/Importer.ts
- packages/core/src/importers/SpecImporter.ts
- packages/core/src/loaders/JsonLoader.ts
- packages/core/src/loaders/Loader.ts
- packages/core/src/loaders/LoaderFactory.ts
- packages/core/src/loaders/YamlLoader.ts
- packages/core/tests/SpecImporter.spec.ts
- packages/editor/src/editor/BaseTreeParser.ts
- packages/editor/tests/oas2.spec.ts
- packages/editor/tests/oas3.spec.ts
> feat(core): optional format parameter on import

- packages/validator/package.json
- packages/validator/src/validator/HarValidator.ts
- packages/validator/src/validator/OASValidator.ts
- packages/validator/src/validator/PostmanValidator.ts
- packages/validator/src/validator/Validator.ts
- packages/validator/tests/error-humanizer.spec.ts
- packages/validator/tests/har.spec.ts
- packages/validator/tests/oas.spec.ts
- packages/validator/tests/postman.spec.ts
> fix(validator): rework usages of deprecated types package

- packages/editor/src/editor/postman/PostmanBodyParser.ts
- packages/editor/tests/fixtures/postman-sample1.result.json
> fix(editor): proper json pointer for body parameters in postman

- packages/oas/src/converter/DefaultConverter.ts
- packages/oas/src/errors/ConvertError.ts
- packages/oas/src/errors/index.ts
- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/missed-host.oas.yaml
- packages/oas/tests/fixtures/missed-servers.oas.yaml
> feat(oas): augment errors with error location info

- packages/oas/src/index.ts
- packages/postman/src/index.ts
> fix(*): export converter error classes 

- packages/core/src/index.ts
- packages/core/src/utils/url.ts
- packages/core/tests/url.spec.ts
- packages/oas/src/converter/DefaultConverter.ts
- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/convert-error-on-url.oas.yaml
- packages/oas/tests/fixtures/convert-error-on-url.swagger.yaml
- packages/oas/tests/fixtures/github.swagger.result.json
- packages/oas/tests/fixtures/petstore.oas.result.json
- packages/oas/tests/fixtures/refs.oas.result.json
- packages/postman/src/converter/DefaultConverter.ts
- packages/postman/tests/DefaultConverter.spec.ts
> feat(*): check result URL correctness in converters

- packages/openapi-sampler/src/samplers/StringSampler.ts
- packages/openapi-sampler/tests/string.spec.ts
> fix(openapi-sampler): errors on string constrain violations

- packages/capture/src/builder/DefaultHarBuilder.ts
- packages/core/src/importers/BaseOASImporter.ts
- packages/core/src/importers/HARImporter.ts
- packages/core/src/importers/OASV2Importer.ts
- packages/core/src/importers/OASV3Importer.ts
- packages/core/src/importers/PostmanImporter.ts
- packages/oas/src/converter/DefaultConverter.ts
> fix(*): use stricter type prechecks

- packages/openapi-sampler/tests/number.spec.ts
- packages/validator/src/schemas/openapi/v2.0.0.json
- packages/validator/tests/fixtures/oas2.petstore.json
> fix(validator): proper type of exclusiveMinimum/exclusiveMaximum for oas2

- packages/oas/src/converter/DefaultConverter.ts
- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/query-params.oas.result.json
- packages/oas/tests/fixtures/query-params.oas.yaml
> test(oas): oas query parameters style and explode tests

- packages/oas/src/converter/DefaultConverter.ts
- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/query-params.swagger.result.json
- packages/oas/tests/fixtures/query-params.swagger.yaml
> fix(oas): handling of swagger `collectionFormat`

- packages/core/src/utils/url.ts
- packages/oas/src/converter/DefaultConverter.ts
- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/params-path.swagger.result.json
- packages/oas/tests/fixtures/params-path.swagger.yaml
> fix(oas): handling of swagger `collectionFormat` in path and query parameters 

- packages/oas/src/converter/BaseUrlParser.ts
- packages/oas/src/converter/DefaultConverter.ts
- packages/oas/src/converter/ParamsSerializer.ts
- packages/oas/src/converter/Sampler.ts
- packages/oas/src/converter/subconverters/HeadersConverter.ts
- packages/oas/src/converter/subconverters/PathConverter.ts
- packages/oas/src/converter/subconverters/PostDataConverter.ts
- packages/oas/src/converter/subconverters/QueryStringConverter.ts
- packages/oas/src/converter/subconverters/SubConverter.ts
- packages/oas/src/converter/subconverters/SubPart.ts
- packages/oas/src/converter/subconverters/index.ts
- packages/oas/src/types/index.ts
- packages/oas/src/utils/Params.ts
- packages/oas/src/utils/index.ts
> refactor(oas): split monolithic `DefaultConverter`

- packages/core/src/importers/ImporterType.ts
> fix(core): make `ImporterType` enum values exportable

- packages/editor/src/editor/oas/v3/OasV3ParameterObjectsParser.ts
- packages/editor/tests/fixtures/oas3-param-values-precedence.json
- packages/editor/tests/fixtures/oas3-param-values-precedence.result.json
- packages/editor/tests/oas3.spec.ts
- packages/oas/src/converter/parts/Sampler.ts
- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/params-values-precedence.oas.json
- packages/oas/tests/fixtures/params-values-precedence.oas.result.json
> fix(*): align possible origins of oas3 parameter values and their precedence

- packages/oas/src/converter/parts/postdata/PostDataConverter.ts
- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/params-body-default.swagger.json
- packages/oas/tests/fixtures/params-body-default.swagger.result.json
> fix(oas): do not encode json body if it is already a string

- packages/oas/src/converter/parts/postdata/PostDataConverter.ts
- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/params-body-default.oas.result.json
- packages/oas/tests/fixtures/params-body-default.oas.yaml
> fix(oas): use oas3 request body content example if exists

- packages/core/src/utils/url.ts
- packages/core/tests/url.spec.ts
- packages/oas/tests/fixtures/empty-schema.oas.result.json
- packages/oas/tests/fixtures/params-path.oas.result.json
- packages/postman/tests/DefaultConverter.spec.ts
- packages/postman/tests/fixtures/Salesforce APIs.postman_collection.result.json
- packages/postman/tests/fixtures/trailing-slash.postman_collection.json
- packages/postman/tests/fixtures/trailing-slash.postman_collection.result.json
> fix(core): prevent removing a trailing slash

- packages/oas/src/converter/parts/headers/HeadersConverter.ts
- packages/oas/tests/DefaultConverter.spec.ts
> fix(oas): handling of non-existing security schema references

- packages/oas/src/converter/parts/headers/Oas3HeadersConverter.ts
- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/missing-security.oas.result.json
- packages/oas/tests/fixtures/missing-security.oas.yaml
- packages/oas/tests/fixtures/missing-security.swagger.result.json
- packages/oas/tests/fixtures/missing-security.swagger.yaml
> fix(oas): parsing security schemes on missing components section

- packages/openapi-sampler/src/samplers/StringSampler.ts
- packages/openapi-sampler/tests/string.spec.ts
> feat(openapi-sampler): add support for extra format options

- packages/oas/src/converter/parts/headers/Oas2HeadersConveter.ts
- packages/oas/tests/fixtures/github.swagger.result.json
- packages/oas/tests/fixtures/params-header.oas.result.json
- packages/oas/tests/fixtures/params-header.oas.yaml
- packages/oas/tests/fixtures/params-header.swagger.result.json
- packages/oas/tests/fixtures/params-header.swagger.yaml
> fix(oas): force string header value

- packages/oas/src/converter/DefaultConverter.ts
- packages/oas/src/converter/SubPart.ts
- packages/oas/src/converter/parts/SubConverterFactory.ts
- packages/oas/src/converter/parts/cookies/CookiesConverter.ts
- packages/oas/src/converter/parts/cookies/Oas2CookiesConverter.ts
- packages/oas/src/converter/parts/cookies/Oas3CookiesConverter.ts
- packages/oas/src/converter/parts/cookies/index.ts
- packages/oas/tests/DefaultConverter.spec.ts
- packages/oas/tests/fixtures/cookies.oas.result.json
- packages/oas/tests/fixtures/cookies.oas.yaml
> feat(oas): add support for cookie parameters

- packages/oas/src/converter/parts/postdata/BodyConverter.ts
> fix(oas): prevent ReDoS in the `BodyConverter`

- packages/core/src/importers/OASV3Importer.ts
- packages/core/tests/OASV3Importer.spec.ts
> feat(core): able to import OAS 3.1 document
